markdown: rdiscount
title: KanjiVG
author: Ulrich Apel
project-links:
- text: Home
  url: index.html
  icon: home
- text: Download
  url: https://github.com/KanjiVG/kanjivg/releases
  icon: download
- text: Repository
  url: https://github.com/KanjiVG/kanjivg
  icon: list
- text: Listing
  url: listing.html
  icon: list
- text: Issues
  url: https://github.com/KanjiVG/kanjivg/issues
  icon: exclamation-sign
format-links:
- text: Files
  url: files.html
  icon: info-sign
- text: SVG Format
  url: svg-format.html
  icon: info-sign
- text: Stroke types
  url: stroke-types.html
  icon: info-sign
- text: Variants
  url: variants.html
  icon: info-sign
- text: Radicals
  url: radicals.html
  icon: info-sign
- text: Glossary
  url: glossary.html
  icon: info-sign
- text: References
  url: ref.html
  icon: info-sign
community-links:
- text: Mailing list
  url: http://groups.google.com/group/kanjivg
  icon: list-alt
- text: Projects using KanjiVG
  url: projects.html
  icon: asterisk
- text: Related projects
  url: related.html
  icon: heart
tool-links:
- text: Viewer
  url: viewer.html
  icon: picture
- text: Known problems
  url: known-problems
  icon: info-sign
